[build]
  publish = "dist"
  command = "npm run build"
  
[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://data-entry-backend-pkeo.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://data-entry-backend-pkeo.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200